### ISSUE TITLE
Offering Graphics Ideas (feature requests)

### ISSUE THREAD

**Issue by CCV54** [yoki123/hodoku#1]
Hi people,

It's been a while since Hobiwan expressed a desire for some better looking filter digits. I didn't realise this project was continuing on here. Great to see tho!

Here is some of my work
[Sudoku_Filter.zip](https://github.com/yoki123/hodoku/files/5148207/Sudoku_Filter.zip)
![ov078](https://user-images.githubusercontent.com/26049501/91680941-4560a100-eb90-11ea-96f5-e0759a979243.png)
The mask for ColorKu especially, in my view, could do with the improvement. That was my work originally too. (CCV)

I made a variety of colour adjustments as well, including completely reworking colours for ColorKu.
First tho, the Pen colours mainly because colours 3b and 4b look too similar to me.

R:G:B
Pen A-1 255:187:80,   A-2 247:214:155
Pen B-1 176:164:239, B-2  209:202:244
Pen C-1 255:145:165, C-2 255:205:212
Pen D-1 137:216:255, D-2 187:248:255
Pen E-1 122:239:122, E-2 178:255:178

ColorKu:
1 234:20:45
2 252:147:0
3 220:205:0
4 65:205:0
5 4:232:115
6 0:193:219
7 2:52:221
8 151:5:239
9 228:2:204

Filter, for ColorKu especially, but works OK in Sudoku too I reckon.
200:221:227

And, just a thought, ALS:
1 113:213:180
2 253:184:244
3 146:233:242
4 174:225:160

**Comment by CCV54** [comment]
Colours for Hints, also mainly to work better in ColorKu:
Normal 63:218:101
To delete 255:94:106
Fins 127:187:255
Endo-Fins 213:170:255

**Comment by yoki123** [comment]
Hello @CCV54
This project is not official, and I am not professional on sudoku neither .
I copied the project source from http://hodoku.sourceforge.net/ and made some change for my own usage.

**Comment by CCV54** [comment]
Hi @yoki123 
Yes, I'm very familiar with the original project. Some of these changes were in the works for that, but, due to illness, didn't make it into any official release.

What drew my attention to your project is the fact that the Report error function still points to https://sourceforge.net/p/hodoku/bugs-and-feature-requests/ and someone reported a problem with this version there.

I love the program and have put a lot of work into what are admittedly mostly cosmetic features. I'd love to see them properly implemented too. Changes to images, filter numbers, ColorKu mask etc. I can make for myself. I actually hired professional programmers for things I can't do and have the results in JAR format. What I can't do now is set any colour changes, since then, as default, plus a couple of feature requests implemented in my unofficial version.

Seeing as version 2.3.0 is publicly available, and at least one other person is using it; Would you be at all inclined to consider making such changes as I have suggested?

**Comment by CCV54** [comment]
That's OK, @yoki123. Thanks anyway.
Btw, Hobiwan wasn't working as a Sudoku professional either when he produced the source code upon which you rely.

This is what I have atm, and it addresses some issues (including changes to Filter numbers and ColorKu mask I mentioned) - the bug in ColorKu Candidate Colours selection, added confirmation dialogue for Create New Sudoku and Concrete Hint for XYZ-Wing displaying 3 candidates. 
[HoDoKu_221.zip](https://github.com/yoki123/hodoku/files/5154238/HoDoKu_221.zip)

I'm very far from thinking about additional solving techniques. Still, I would like to figure out how to set colour changes as as Default. Looks to me like NetBeans might allow editing .class files. Idk, and it takes me a lot of time and effort to get my head around using such an app.. Can you offer any better suggestion?

Excelsior JET, a long time ago, I have used to package .jar into .exe and then to a Windows Installer. The installer seemed like an an awfully big file tho, and now I'd have to relearn the whole process. Far from easy, for me. Do you have any better idea about that too?

Regards, Colin.

**Comment by CCV54** [comment]
Hi again @yoki123 
Sorry to bother you, but the more I look into this the more complex, confusing and frustrating it becomes for me. I could do with a little help.
I know you said you are not "professional" at this, but you are obviously quite adept - even going so far as packaging the .jar into .exe and windows installer!
All I really need is the listed colours set as default. Above and beyond that, an .exe and windows installer version would be great too.
I would willingly pay for your time, as, otherwise, I would need to hire programmers. Payment is easily arranged, either through PayPal or direct EFT to a nominated account.

Regards, Colin.

**Comment by yoki123** [comment]
Ok, Colin. I think you misunderstand me.  

Honestly, I am a backend developer and I know rarely about Java or Java application developing. I just made some extremely basic changes several years ago. You can see the code from [commit: f77c7c](https://github.com/yoki123/hodoku/commit/7ad1447d3406994f7fb127ebe0fdfbe2c5f77c7c). So your feature requests is so hard for me. Unfortunately, I cann't find someone can do this. I'm sorry I can't help you.

On the other hand, I find out that @PseudoFish forked the project, made a lot changes and released 2.3.0. I think you are looking for him, not me. But there is no `Issue` button on his fork, so that we cann't concat to him. Maybe you can make a pull request to his project for concating to him.

**Comment by CCV54** [comment]
OK, yoki, thank you for the clarification. Perhaps a pull request addressed @PseudoFish is what I need to do. Looking at his profile, I think you're right. Now way to download his release versions, let alone contact him.  :\

**Comment by CCV54** [comment]
Oh, wait.. If I go to https://github.com/PseudoFish/Hodoku/releases/tag/2.3.0, then I can see "pull request" available. Not sure how my previous pull requests came to be addressed to you.

**Comment by CCV54** [comment]
Still can't contact @PseudoFish by any means, unless he can already see my pull requests.

**Comment by 1to9only** [comment]
I posted about PseudoFish's Hodoku on the enjoysudoku forum where there is a good bunch of HoDoKu users:
http://forum.enjoysudoku.com/pseudofish-s-hodoku-t38159.html

PseudoFish:Hodoku is 124 commits ahead of yoki123:master - reportedly mostly GUI improvements.

CCV54's Pull Request appears to update yoki123:master to PseudoFish:Hodoku level code - I'm not sure if yoki123 wants this.

Ideally, CCV54 should fork the Pseudofish repository (it's the most recent!), and apply his own changes.

Optionally (if PseudoFish is not contactable), I can offer to fork Pseudofish and make a few changes (improvements!) as per Colin's notes.

Note: I'm not a big HoDoku user, but I can build java code...

**Comment by CCV54** [comment]
Hi @1to9only 
I don't know about contacting @PseudoFish, doesn't seem possible, but my pull requests do appear on his 2.3.0 release.

> CCV54's Pull Request appears to update yoki123:master to PseudoFish:Hodoku level code - I'm not sure if yoki123 wants this.
> 
> Ideally, CCV54 should fork the Pseudofish repository (it's the most recent!), and apply his own changes.
> 
> Optionally (if PseudoFish is not contactable), I can offer to fork Pseudofish and make a few changes (improvements!) as per Colin's notes.
> 
> Note: I'm not a big HoDoku user, but I can build java code...

Sounds great, if you could please help me!
The graphics, filter numbers and ColorKu mask, are easy to change using 7zip to expand the "img" directory. 
Otoh, trying to extract .class files has proved beyond my ability to understand. There's a whole bunch of ColorConfig...class files in the "sudoku" folder. Not sure which might be applicable, but I would love to have my current colour configuration set as default. 

Btw, what I have done is based directly upon the official 2.2.0 release. Not sure I want Pseudofish's GUI changes either.

**Comment by 1to9only** [comment]
@CCV54 
Check your email. I wish to take the discussion away from @yoki123's repository.
My apologies to yoki123.
@yoki123 
The issue and pull request should be closed/deleted to avoid further pollution!
Make sure you don't (accidentally) merge Pseudofish's changes into your repository.
Regards.
1to9only.

**Comment by CCV54** [comment]
P.S. @1to9only 
I forgot to mention, 'my' version has the bug in ColorKu colour selection fixed. Plus, confirmation Dialogue for Create new Sudoku and Concrete hint for XYZ-Wing displaying _three_ candidates. All features I very much want to keep. So, it's only colour changes I need, atm.. Thank you.

**Comment by CCV54** [comment]
@1to9only 
I have received and accepted your invitation to "Discuss", privately.
@yoki123 I also apologise.
